name = "field"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXTAUTH_URL = "https://yourdomain.com"
R2_BUCKET_NAME = "field-media"
NODE_ENV = "production"

[[r2_buckets]]
binding = "FIELD_MEDIA"
bucket_name = "field-media"
